### PR TITLE
Add Panel 0.14 release blog

### PR DESCRIPTION
**Pull request by philippjfr**

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
# Review

## Item 1: Markdown

Write blob in Markdown. Github does not enable me to add comments to notebooks and images.

## Item 2: Image header

Add header `Panel - XGBoost in Webassembly` or similar to image. Users would not know why the picture in itself is there.

image

## Item 3: mention webassembly in workflow

*standalone data app running in the browser or on a server*

image

## Item 4: user readable font

Same comment as last blog post. The font is not readable.

image

## Item 5: change formulations to why and what not how. 

Change

- Support for converting your apps & documentation to run in the browser with Pyodide & PyScript.
- Add ability to cache your callbacks with the new pn.cache decorator.
- Easily defer loading of expensive components using the defer_load option.
- Register a global exception handler to log errors or notify your users that something went wrong.
- We finally have our own CDN (https://cdn.holoviz.org/), improving loading speeds and reliability.
- Improving docstrings, adding types and improving the documentation.
- A new server implementation allowing you to run Panel apps inside Jupyter kernels.
- Major improvements in robustness of the Tabulator widget.

to

You can now easily

- run your apps and documentation in in the browser. No server required!
- speed up your application by caching with the new easy to use `pn.cache` decorator.
- provide awesome error messages to your users via a **global exception handler**.
- display large tables with a much more robust Tabulator widget.
- preview your apps inside Jupyter using custom Jupyter kernels.
- find the information you need via improved docstring, type annotations and online documentation.
- build data apps that loads faster because we now have **our own, faster CDN** (https://cdn.holoviz.org/) to serve images, css and js files used in your data app.

**Comment by MarcSkovMadsen** [comment]
## Item 6: Mention the pain it solves

Change

Panel lets you write dashboards and other applications in Python that are accessed using a web browser. Typically, the Python interpreter runs as a separate Jupyter or Bokeh server process, communicating with JavaScript code running in the client browser. However, it is now possible to run Python directly in the browser, with no separate server needed!

To

Panel lets you write dashboards and other applications in Python that are accessed using a web browser. You typically have to deploy your Panel app to a web server. This introduces some pains

- deployment of a web server is a separate skill that takes time and is costly
- the communication between the server and browser introduces latency, it takes time to communicate back and forth.

Panel 0.14 provides a game changer. It is now possible to run Panel Apps directly in the browser, with no separate server needed and super-fast response times!

**Comment by philippjfr** [comment]
Thanks, all extremely valuable feedback. Any suggestions on a better font? Was just in the process of looking for one.

**Comment by MarcSkovMadsen** [comment]
## Item 7: Mention big download just before the app links.

## Item 8:

Make hvplotExplorer app responsive (and make the axis format nicely or make it easy to get the right formatting.)

image

**Comment by philippjfr** [comment]
Just a few comments on your items:

1. I'd like to overhaul the blog generally but that's not happening today.
2. Will do.
3. Done
4. Suggestions for a better font very welcome
5. Done
6. Done
7. Done
8. That's an hvPlot change but to be clear I'm not sure if it's even desirable or the correct thing to do. Setting up fixed or responsive sizing is part of what the explorer lets you configure and responsive is not the default for the explorer.

**Comment by MarcSkovMadsen** [comment]
Item 9: Add `**Panel** to the `site` or `title` of all apps

It would be so bad if people got excited but did not know it was a Panel app.

image

The images will be available on the internet in many contexts outside the blog. It needs to be clear its a panel app.

Item 10: Make it easy to share the blog post and to show support by giving a ⭐

Provide some links that will open twitter, linkedin and github. The social media links can be prefilled I believe with some statement.

Item 10: I just also ❤️ the `@pn.cache`. Please provide example with `pn.bind`

The statement 

image

is not clear for beginners. What should go first? Please provide a specific example.

**Comment by MarcSkovMadsen** [comment]
> 8. That's an hvPlot change but to be clear I'm not sure if it's even desirable or the correct thing to do. Setting up fixed or responsive sizing is part of what the explorer lets you configure and responsive is not the default for the explorer.

But please make the Panel app responsive! It looks unprofessional if its not responsive.

**Comment by MarcSkovMadsen** [comment]
That was it for now. Panel has come a long way. You have done amazing things with it @philippjfr 💪

**Comment by MarcSkovMadsen** [comment]
## Item 11 Add vision

The roadmap is a bit technical. What would be more interesting before the Roadmap is a short summary of the vision. For example

### Summary

Panel 1.0 should make it really, really simple and fun to create performant data apps for Pythonistas across development and deployment environments. To achieve this, we want to

- Finalize the core *apis* of Panel to make them simple and efficient to use
- Heavily improve the documentation. We started by building the technical foundation. Now we are ready for the documentation.
- identify performance bottlenecks and remove them.
- Upgrade to Bokeh 3.0 which will provide a much better foundation for styling and performance
- Solve lots of minor bugs reported by our users

**Comment by philippjfr** [comment]
@MarcSkovMadsen Could you force reload https://blog.holoviz.org/panel_0.14.html and see what you think of the new font?

**Comment by MarcSkovMadsen** [comment]
Wow. The new font looks amazing.

For the next version of Panel and blog it might be an idea to use the new dark style for the code cells and add a *copy-paste* button 😄 . It just another improvement. Not needed now.

**Comment by MarcSkovMadsen** [comment]
You could consider using another background like url('https://preview.redd.it/9oi428ohy7t21.png?auto=webp&s=5051b77d33e85446b6492a1e02725c6729777d4f'). It would make the text stand out.

image

**Comment by MarcSkovMadsen** [comment]
I would also remove the #header-wrapper:before background.

image

**Comment by MarcSkovMadsen** [comment]
Please consider trying out the background above @philippjfr . To me it makes a world of a difference.

**Comment by MarcSkovMadsen** [comment]
## Item 14 Make it 3

image

**Comment by MarcSkovMadsen** [comment]
## Item 17

You should update the code of the example to be what is shown in gif.

image

Then you will not risk disappointing users or spend time on support 😄

**Comment by philippjfr** [comment]
>You should update the code of the example to be what is shown in gif.

I did.

**Comment by MarcSkovMadsen** [comment]
## Add links to WebAssembly documentation all over the place

I can't find any links to the WebAssembly documentation. Huge mistake. People will want to take the next step and figure out how to do this. Please add links all over the place.

**Comment by MarcSkovMadsen** [comment]
## Item 19: Make sure there is an easy to find and click link for more information about each new feature.

Users need help to figure out how to take the next step. They might not be able to go to the Panel website and find it.

**Comment by MarcSkovMadsen** [comment]
## Item 20: Try it out here

The interactive docs is amazing. Please help users navigate to it by adding a link to the blog post with a comment like "Try it out here"

image

**Comment by MarcSkovMadsen** [comment]
## Item 22 Release on LinkedIn.

A lot of people on Linkedin are interested in Panel when we show them something. This is a big opportunity to give them something and potentially get more followers.

**Comment by philippjfr** [comment]
>A lot of people on Linkedin are interested in Panel when we show them something. This is a big opportunity to give them something and potentially get more followers.

I think I gave you access? If not I'd be happy to. You're way better at this than me :)

**Comment by MarcSkovMadsen** [comment]
We are not at 50 *Items* yet 😄

**Comment by MarcSkovMadsen** [comment]
## Item 23

Move the live examples from `pyviz-dev` to `pyviz` (or somewhere else).

image

**Comment by philippjfr** [comment]
They have moved, just need to update the links, see: https://panel.holoviz.org/pyodide/index.html

**Pull request merged**
